version: '3.7'
services:
  site:
    container_name: docsy
    platform: linux/amd64
    # Change from 3.8 to 4.2 or 'latest'
    image: jekyll/jekyll:4.2.2
    command: jekyll serve --watch --drafts
    volumes:
      - "./:/srv/jekyll"
      - "./vendor/bundle:/usr/local/bundle"
    ports:
      - "4000:4000"